# Target specific macros
TARGET = sorting_machine_OSEK
TARGET_SOURCES = \
	sorting_machine.c
TOPPERS_OSEK_OIL_SOURCE = ./sorting_machine.oil

# Don't modify below part
O_PATH ?= build
include ../../../nxtOSEK/ecrobot/ecrobot.mak
